repo:
  - '*'

github:
  - .github/**/*

application:
  - application/**/*

docs:
  - docs/**/*

extensions:
  - extensions/**/*

frontend:
  - frontend/**/*

scripts:
  - scripts/**/*

tests:
  - tests/**/*
